def row(name, old, new, note):
    return dict(name=name, old=old, new=new, note=note)


modules = [
    dict(key='terminal-card', title='终端信息卡片', old='19811:268258', new='19811:268334', height=250,
         subtitle='详情入口、最近充电提示与包租说明加大一号',
         rows=[row('终端详情入口',12,13,'右侧「终端详情」入口单独圈选。'),
               row('最近充电提示',12,13,'「2分钟前有人充过」整句加大，包含时间数字。'),
               row('终端包租说明',12,13,'底部包租时间与自动停充说明整段加大。')],
         marks=[dict(label='终端详情入口',indices=[4],old=12,new=13,route='right',ly=86),
                dict(label='最近充电提示',indices=[3],widths=[94,102],old=12,new=13,route='right',ly=140,lane=405),
                dict(label='终端包租说明',indices=[5],old=12,new=13,route='right',ly=194)],
         note='「空闲中」仍为 14，终端名称仍为 18，「快充」标签仍为 12.5。'),
    dict(key='terminal-price', title='价格信息', old='19811:268410', new='19811:268467', height=266,
         subtitle='主标题、当前时段说明与时间加大一号',
         rows=[row('主标题「价格信息」',15,16,'卡片主标题加大一号。'),
               row('当前时段与时间',12,13,'右侧「当前时段」与「15:00-16:00」一起调整，整组圈选。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='当前时段与时间',indices=[2,3],old=12,new=13,route='right',ly=76)],
         note='单位、充电价与会员价数字、开通会员横幅均维持原字号。'),
    dict(key='terminal-parking', title='停车参考价', old='19811:268899', new='19811:268925', height=224,
         subtitle='主标题、停车收费规则与补充说明加大一号',
         rows=[row('主标题「停车参考价」',15,16,'卡片主标题加大一号。'),
               row('停车收费说明',12,13,'免费时长、超时收费及临时牌照限制整段一起加大。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='停车收费说明',indices=[1],old=12,new=13,route='right',ly=100)],
         note='「充电爱车」仍为 14，车牌信息仍为 12。'),
    dict(key='terminal-overtime', title='超时占用费', old='terminal-overtime-old', new='terminal-overtime-new', height=213,
         subtitle='主标题、收费规则与不收取状态分别校准',
         rows=[row('主标题「超时占用费」',15,16,'收费与不收取两种状态的主标题均加大一号；只圈上方一个代表。'),
               row('超时费收费规则',12,13,'单价、计费单位与免费时长一起调整。'),
               row('不收取状态',12,13,'右侧「不收取」单独圈选，覆盖免收场景。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='超时费收费规则',indices=[1],old=12,new=13,route='right',ly=90),
                dict(label='不收取状态',indices=[3],old=12,new=13,route='right',ly=146)],
         note='上方为收费状态，下方为不收取状态；两种状态采用相同的标题字号。'),
    dict(key='terminal-coupons', title='卡券与套餐', old='19811:268979', new='19811:269002', height=205,
         subtitle='主标题、套餐与卡券右侧摘要加大一号',
         rows=[row('主标题「充电套餐」「卡券」',15,16,'两个主标题均加大一号；只圈「充电套餐」一个代表。'),
               row('套餐摘要信息',12,13,'「免服务费充电」与剩余度数一起调整。'),
               row('卡券可用摘要',12,13,'右侧「3张可用」单独圈选，包含数量和状态文字。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='套餐摘要信息',indices=[1,2],old=12,new=13,route='right',ly=70),
                dict(label='卡券可用摘要',indices=[6],widths=[43,47],x_offsets=[152,148],old=12,new=13,route='right',ly=128)],
         note='自动抵扣说明与「设置」仍为 12。'),
    dict(key='terminal-payment', title='支付方式', old='terminal-payment-old', new='terminal-payment-new', height=573,
         subtitle='主标题、支付方式选择标签与辅助信息分别校准',
         rows=[row('主标题「支付方式」',15,16,'预付费、余额付与企业账户三种状态的主标题同步调整；只圈上方一个代表。'),
               row('支付方式选择标签',12,13,'先充后付、预付费、余额付、企业账户、第三方账户按同类标签统一为 13；只圈上方「余额付」一个代表。'),
               row('预付金额选择入口',12,13,'预付费状态右侧「请选择预付金额」加大一号。'),
               row('限定金额说明',12,13,'余额付状态的「限定金额」文字加大；输入金额维持原字号。'),
               row('余额不足停充提示',12,13,'「余额不足5元时将停止充电」整句加大，包含金额数字。'),
               row('切换账户入口',12,13,'企业账户状态右侧「切换账户」入口加大。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='支付方式选择标签',indices=[3],old=12,new=13,route='right',ly=77),
                dict(label='预付金额选择入口',indices=[6],old=12,new=13,route='right',ly=130),
                dict(label='限定金额说明',indices=[20],old=12,new=13,route='custom',lead='top',bend_y=266,ly=258),
                dict(label='余额不足停充提示',indices=[23],old=12,new=13,route='right',ly=337),
                dict(label='切换账户入口',indices=[33],old=12,new=13,route='right',ly=445)],
         note='三种支付状态按原稿顺序展示。企业账户场景横向列表屏外的「余额付」在当前稿中仍为 12，开发时也应按同类标签统一为 13。可用余额、金额数字、余额构成、企业名称及账户余额维持原字号。'),
    dict(key='terminal-invoice', title='发票信息', old='19811:269512', new='19811:269523', height=160,
         subtitle='主标题、发票类型与抬头摘要加大一号',
         rows=[row('主标题「发票」',15,16,'卡片主标题加大一号。'),
               row('发票类型与抬头',12,13,'右侧「普票(」与「个人」两段文字加大；只圈实际调整的文字。')],
         marks=[dict(label='卡片主标题',indices=[0],old=15,new=16,route='top',ly=24),
                dict(label='发票类型与抬头',indices=[1,2],old=12,new=13,route='right',ly=89,pad=0)],
         note='当前校准稿的末尾右括号「)」仍为 12；自动开票说明仍为 12。'),
    dict(key='terminal-insurance', title='特无忧服务', old='19811:269534', new='19811:269562', height=177,
         subtitle='服务名称由 14 调整为 15',
         rows=[row('特无忧服务名称',14,15,'只调整「特无忧服务」标题，原字重保持不变。')],
         marks=[dict(label='特无忧服务名称',indices=[0],old=14,new=15,route='top',ly=28)],
         note='权益说明仍为 12；划线价、购买金额、人民币符号与「/次」均维持原字号。'),
]

for number, mark in enumerate((mark for module in modules for mark in module['marks']), 1):
    mark['number'] = f'{number:02}'
